project:
  type: website
  output-dir: docs


website:
  title: "Hannah and Meghan's Christmas Adventure"
  site-url: https://markhanly.github.io/christmas-market-adventure/
  image: /docs/images/tipsycake-side-profile.png
  favicon: images/favicon.ico
  page-footer:
    left: "[Go back to the start 🎄](index.html)"
    right: "[About](about.html)"
  

format:
  html:
    theme: 
      - sketchy
      - custom.scss
    css: styles.css
    toc: false
    smooth-scroll: true
    licence: "CC BY-NC"

